name: Deploy to Server

on:
  push:
    branches:
      - main # 设置为您的默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@152.32.220.250 "cd /home/www/book-leaf && git pull origin main && pnpm i && pnpm run build"
